---
title: "RMarkdown-Covid19-Vaccine-Analysis"
author: "18F-0421"
date: "12/20/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown


```{r}
library(ggplot2)
library(scales)
library(tidyverse)
library(data.table)
library(stringr)
library(summarytools)
```

## Including Plots


```{r}

vaccine_data<-fread(file = "CountryviseVaccinations.csv")
head(vaccine_data)
str(vaccine_data)
dim (vaccine_data)
vaccine_data_copy <- vaccine_data[,1:13]
colnames(vaccine_data_copy)
data.frame("TotalNAs" = colSums(is.na(vaccine_data_copy))) %>%
  mutate ("PercentageOfNA" = (colSums(is.na(vaccine_data_copy))/dim(vaccine_data_copy)[1]) %>% 
            round (3) * 100)

vaccine_data_copy[is.na(vaccine_data_copy)] = 0

remove_countries = c('England','Northern Ireland','Scotland','Wales','Falkland Islands','Faeroe Islands','Isle of Man','Cayman Islands','Saint Helena','Saint Lucia','Saint Vincent and the Grenadines','Saint Kitts and Nevis')

vaccine_data_copy <- vaccine_data_copy %>%
  filter (!country %in% remove_countries) 

unique(vaccine_data_copy$country)
vaccine_data_copy$vaccines <- str_replace_all(vaccine_data_copy$vaccines, " ","")
# removing spaces
vaccine_val<- unique(vaccine_data_copy$vaccines)
vaccine<- vector()

for (i in vaccine_val){
  for (j in strsplit(i, ",")){
    vaccine<- c(vaccine, j)
  }
}
vaccine_used<- unique(vaccine)
vaccine_used




vaccine_data_val <- data.frame(matrix(ncol = length(vaccine_used), nrow = 0))
for (i in vaccine_data_copy$vaccines){
  vaccine_data_val<- rbind(vaccine_data_val, Vectorize(grepl, USE.NAMES = TRUE)(vaccine_used, str_replace_all(i," ","")))
}
vaccine_data_val[vaccine_data_val == TRUE] = 1
vaccine_data_val[vaccine_data_val == FALSE] =0
colnames(vaccine_data_val) <- paste0(unique(vaccine))
vaccine_in_countries<- vaccine_data_val %>%
  mutate(country = vaccine_data_copy$country)%>%
  group_by(country)%>%
  summarise_all(sum)

data <- data.frame("No_of_countries"= apply(vaccine_in_countries[-1],2, function(c)sum(c!=0)))
cbind("Vaccine"=row.names(data),data) %>%
  ggplot(mapping=aes(x=reorder(Vaccine, -No_of_countries), y=No_of_countries, fill = Vaccine, alpha=2.5))+
  geom_col() +
  labs(x = "Vaccines", y = "No. of Countries", title  = "Countries using vaccines")+
  geom_text(aes(label = No_of_countries), vjust=-2.5)+
  theme_minimal()
```

